### ISSUE TITLE
AddToRoleAsync throw "Role X does not Exist"

### ISSUE THREAD

**Issue by francescocristallo** [dlmelendez/identitycosmosdb#3]
I tried to add a Role to the user during Registration using 

`await _userManager.AddToRoleAsync(user, "Admin");`

but an exception is thrown "The role Admin does not exist".

Any docs on how to add a role?
Thanks

**Comment by dlmelendez** [comment]
@francescocristallo you will need to create the role first using the RoleManager before you can add it to your User. Take a look at this test helper for an example: https://github.com/dlmelendez/identitycoredocumentdb/blob/master/tests/ElCamino.AspNetCore.Identity.DocumentDB.Tests/UserStoreTests.cs Line 781 AddUserRoleHelper() method.
Thanks,
Dave

**Comment by francescocristallo** [comment]
Thanks Dave!
I created a RoleManager, roles, added roles to users and it works.
The only thing is that roles are created in the same collection as the "ApplicationUsers".

Is there a way to customize it? In the **IdentityConfiguration** object created at Startup there is just one parameter for the identity collection.
If not possible could be considered for a future update.

Thanks for this project!
