### ISSUE TITLE
JsonPropery attribute ignored when generating SQL via LINQ

### ISSUE THREAD

**Issue by pirinit** [dlmelendez/identitycosmosdb#4]
Hi and thanks for this great library :)

I have problems using LINQ to filter(.Where) and project(.Select) on the Users collection exposed byt UserManger class.

I can see that "ElCamino.AspNetCore.Identity.DocumentDB.Model.IdentityUser" is decorated with 
`[JsonObject(NamingStrategyType = typeof(CamelCaseNamingStrategy))]` 
also all of its properties are decorated with 
`[JsonProperty("camelCasePropertyName")]`

But for some reason those attributes are ignored during SQL generation.

As a workaround I can override the properties I need to access in my ApplicationUser class(Inherits from "ElCamino.AspNetCore.Identity.DocumentDB.Model.IdentityUser") and decorate with the same JsonProperty attribute providing the same Property name (PascalCase).

I guess there was a reason for you to add those JsonProperty attributes in the first place, but currently it just doesn't work.
Steps to reproduce. Just add the following lines in an test action in the Account controller in the "samplecore2.mvc" available in this repository.
`var userDBquery = _userManager.Users
                .Where(u => u.Id == id);`

The generated SQL query will filter on "Id" (capital first letter). The same behavior if you use .Select LINQ extension method.

**Comment by dlmelendez** [comment]
Unfortunately, this is an issue with the documentdb sdk library. https://github.com/Azure/azure-documentdb-dotnet/issues/317 I am hoping they will address this soon to respect the JsonProperty name overrides in the Linq query.

**Comment by dlmelendez** [comment]
Fixed in v3.0
