### ISSUE TITLE
[Question] New instance of DocumentClient for non-Identity related queries?

### ISSUE THREAD

**Issue by luizs81** [dlmelendez/identitycosmosdb#5]
Hello David, 

Thanks for great library. I just started a new DocumentDB-based project and I didn't want to hang a SQL database just for authentication/authorization.

This is probably a silly question, but it has puzzling me for a while, as I'm not very experienced with the .NET architecture (I'm coming from Python projects). 

I see that the `IdentityCloudContext` class exposes a `Client` property, which is an instance of `DocumentClient`. Also, I have an `ApplicationDbContext` class that expands the `IdentityCloudContext`, as the documentation suggests. 

Then, my question is: Can (should?) I use my `ApplicationDbContext` class to handle tasks that are not related to identity? (say.. query/insert/update "products"). If yes, how can I do that? I believe that I should wrap this class in a Singleton or something similar.

Or should I create a different class with a different instance of `DocumentClient` to handle those requests? 

Thank you so much in advance!

Cheers!

**Comment by dlmelendez** [comment]
Using the same instance of ApplicationDbContext for other db requests should be fine.
